### ISSUE TITLE
A little typo here

### ISSUE THREAD

**Issue by namco1992** [egek92/JavaCheatSheet#2]
Hi,
Thank you for your excellent work, but I found a little typo here.
>converting calendar to date:
>```java
>Calendar mCal = Calendar.getInstance();
>Date mDate = mDate.getTime();  
>```

I assume what you mean is this:

```java
Calendar mCal = Calendar.getInstance();
Date mDate = mCal.getTime();  
```

**Comment by egek92** [comment]
Exactly, thanks for the heads up :+1:
